
FROM node AS build
#FROM node:20-alpine AS build
RUN apt update && apt install -y iproute2 net-tools tcpdump curl wget htop
WORKDIR /app
COPY ./frontend/package*.json ./

RUN npm install
COPY ./frontend ./
RUN rm ./.env.production

# Build static assets
RUN npm run build

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "5080"]