
FROM node:20-alpine AS build

WORKDIR /app
COPY ./frontend/package*.json ./
RUN npm install
COPY ./frontend ./

# Build static assets
RUN npm run build

# --- Runtime image ---
FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
